# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-15 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0002_auto_20190915_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='info',
        ),
    ]
