# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-16 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0003_auto_20190916_1501'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
