# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-16 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0004_auto_20190916_1527'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
        migrations.AddField(
            model_name='post',
            name='hood_pic',
            field=models.ImageField(blank=True, upload_to='hood/'),
        ),
        migrations.AlterField(
            model_name='hood',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
